### ISSUE TITLE
Captcha Could Not Be Loaded.

### ISSUE THREAD

**Issue by LeafBlowerOwO** [FlashChaser/Open-Source-Battle-Bot#101]
The bot has been working great for the past few days but now im just getting this, any help is appreciated, thanks!
![captcha couldnt be loaded](https://user-images.githubusercontent.com/53071995/61510615-3d0fcb80-a9b9-11e9-8bd5-27615aab046a.JPG)

**Comment by Simopich** [comment]
Managed to solve?

**Comment by LeafBlowerOwO** [comment]
No not really, but I found out if I wait about two hours or use a VPN to set my location somewhere else it works again, very weird.

**Comment by Simopich** [comment]
Oh okay, thanks!
