### ISSUE TITLE
What IS this thing?

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [FlashChaser/Open-Source-Battle-Bot#11]
Was led to here by you using PySimpleGUI in your project.  

Upon inspection, I've determined that I can't figure out at all what your program does.  What's a Battle Bot?  What's with the ciphers?  

I've done some googling and am still at a loss.

Sorry for being so thick.

**Comment by FlashChaser** [comment]
Its a bot for a mobile game! Dokkan Battle! 

Love PySimpleGUI btw.
