### ISSUE TITLE
I keep getting the error ''WinError 10061''

### ISSUE THREAD

**Issue by ZackIsEpic** [FlashChaser/Open-Source-Battle-Bot#19]
I don't know if it's me or the bot, but I can't seem to fix the problem, here*s the full error code:

ProxyError(MaxRetryError("HTTPSConnectionPool(host='ishin-global.aktsk.com', port=443): Max retries exceeded with url: /auth/sign_up (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03CDF550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))"))

Edit: I had to go into regedit and make ''ProxyEnable'' be 0 instead of 1, thanks for trying to help!

**Comment by Veladem** [comment]
```
'<urllib3.connection.VerifiedHTTPSConnection object at 0x03CDF550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'
```
Bandai has refused connection to your IP.

**Comment by ZackIsEpic** [comment]
> ```
> '<urllib3.connection.VerifiedHTTPSConnection object at 0x03CDF550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'
> ```
> 
> Bandai has refused connection to your IP.

I have the same issue trying to do set up pip, so I don't believe that's the issue
