### ISSUE TITLE
Unbound local error

### ISSUE THREAD

**Issue by ssj-spartan** [FlashChaser/Open-Source-Battle-Bot#22]
Getting UnboundLocalError("local variable 'dec_sign' referenced before assignment")
![image](https://user-images.githubusercontent.com/50834353/58025268-322aed00-7b68-11e9-9a4d-fdd230ab24c5.png)
Any ideas?

**Comment by tgeisterfer** [comment]
got the same :(

**Comment by SuicideBooth** [comment]
Me as well

**Comment by SuicideBooth** [comment]
if you type info it says I have 4 stones left but it also says stamina restored every time. Then proceeds not to work.

**Comment by tgeisterfer** [comment]
we need to use the open source bot instead of the precompiled bot to fix the glb stam bug i thinl. but i dno how to install all those pip3 things

**Comment by SuicideBooth** [comment]
do we need a specific program to run the source botÉ

**Comment by Thorax96** [comment]
You have to replace lines 506 and 513, they are incomplete : '/user/recover_act' has to be 
'/user/recover_act_with_stone' and 'https://ishin-global.aktsk.com/user/recover_act' becomes 'https://ishin-global.aktsk.com/user/recover_act_with_stone' or just copy my refill method : 
<code>

def refill_stamina():

    stones = get_user()['user']['stone']
    if stones < 1:
        print(Fore.RED + 'You have no stones left...')
        return 0
    if config.client == 'global':
        headers = {
            'User-Agent': 'Mozilla/5.0 (Android 4.4; Mobile; rv:41.0) Gecko/41.0 Firefox/41.0',
            'Accept': '*/*',
            'Authorization': packet.mac('PUT', '/user/recover_act_with_stone'),
            'Content-type': 'application/json',
            'X-Platform': config.platform,
            'X-AssetVersion': '////',
            'X-DatabaseVersion': '////',
            'X-ClientVersion': '////',
            }
        url = 'https://ishin-global.aktsk.com/user/recover_act_with_stone'
    else:
        headers = {
            'User-Agent': 'Mozilla/5.0 (Android 4.4; Mobile; rv:41.0) Gecko/41.0 Firefox/41.0',
            'Accept': '*/*',
            'Authorization': packet.mac('PUT', '/user/recover_act_with_stone'),
            'Content-type': 'application/json',
            'X-Platform': config.platform,
            'X-AssetVersion': '////',
            'X-DatabaseVersion': '////',
            'X-ClientVersion': '////',
            }
        url = 'http://ishin-production.aktsk.jp/user/recover_act_with_stone'
    
    r = requests.put(url, headers=headers)
    print(Fore.GREEN + 'STAMINA RESTORED')
</code>

**Comment by Thorax96** [comment]
@SuicideBooth yes. They are listed in the main page of this git Other than that just launch the bot with either : "python dokkan.py" on windows or "python3 dokkan.py" on mac/linux

**Comment by SuicideBooth** [comment]
@Thorax96 every time I double click the "python dokkan.py" it immediately opens then closes. Any clue?

**Comment by SuicideBooth** [comment]
I've never used python so I'm pretty confused.

**Comment by Thorax96** [comment]
execute it in terminal/cmd to see what error is thrown @SuicideBooth

**Comment by SuicideBooth** [comment]
@Thorax96 what is the terminal/cmd your talking about? Is it a program or something cuz I just downloaded visual studios if that helps.

**Comment by SuicideBooth** [comment]
Never mind I found the command prompt but I'm not sure how to execute anything. @Thorax96

**Comment by Thorax96** [comment]
@SuicideBooth first navigate to the directory and then
> @SuicideBooth just launch the bot with either : "python dokkan.py" on windows or "python3 dokkan.py" on mac/linux

**Comment by ErJuancas** [comment]
im new in this type of things can u help me

**Comment by ErJuancas** [comment]
@SuicideBooth can uhelp me i dont know how to do i dont understand

**Comment by ssj-spartan** [comment]
@ErJuancas read this https://github.com/FlashChaser/Open-Source-Battle-Bot/issues/25
