### ISSUE TITLE
Z-Battle throwing out errors

### ISSUE THREAD

**Issue by thed24** [FlashChaser/Open-Source-Battle-Bot#27]
Trying to run the z-battle function returns errors like no_condition_to_try_z_battle_is_fulfilled or z_battle_check_point_does_not_exist on global, however the function works fine on japan.

**Comment by FlashChaser** [comment]
> `no_condition_to_try_z_battle_is_fulfilled`
This means you are too low a level or have not completed the necessary stages to finish zbattle.
> `z_battle_check_point_does_not_exist`
This happens if you have not completed prior zbattle missions. So the previous error can cause this to happen.

**Comment by tgeisterfer** [comment]
is there a function to do single zbattles? can only find the completezbattle that does all

**Comment by FlashChaser** [comment]
Not at this stage. I'll add it in when I get some more time. Or if someone else does it Ill merge their pull request. Shouldn't be too hard, all the code is already there more or less.
