### ISSUE TITLE
how do i use this for mac because i downloaded the dokkn bot but whenever i choose to open glb its damaged 

### ISSUE THREAD

**Issue by CloudyyJ** [FlashChaser/Open-Source-Battle-Bot#28]

**Comment by FlashChaser** [comment]
Please provide more information or a screenshot.

**Comment by Defences** [comment]
@FlashChaser 
I have used updated file and codes for the commands file. The GLB stamina refresh bug still remains on Mac os however.

**Comment by Defences** [comment]
The fix ended up being fully deleting the bot and redownloading.
