### ISSUE TITLE
No recovering stamina

### ISSUE THREAD

**Issue by Alfa0732** [FlashChaser/Open-Source-Battle-Bot#29]
Once my stamina is empy it's supposed to auto recharge, but it doesn't.
Anybody else with the problem?

**Comment by Tresava14** [comment]
im having the same problem i wish it would fix

**Comment by FlashChaser** [comment]
This has been fixed on the current development branch.

**Comment by Darpz** [comment]
> This has been fixed on the current development branch.

So how to use it ?
