### ISSUE TITLE
global is not refreshing stamina

### ISSUE THREAD

**Issue by Tresava14** [FlashChaser/Open-Source-Battle-Bot#30]
when i try to make a acc i get so far then my stamina runs out this is a huge bug that can ruin many peoples buissnesses please fix this as soon as possible @FlashChaser #29

**Comment by FlashChaser** [comment]
This has been fixed on the current development branch.

**Comment by FlashChaser** [comment]
Remember this is free software. There are no guarantees or warranties provided for commercial use.
