### ISSUE TITLE
For Mac Users, how to create a shortcut on desktop to go straight into the bot?

### ISSUE THREAD

**Issue by Defences** [FlashChaser/Open-Source-Battle-Bot#31]
Currently on mac, to access the bot we have to open terminal then copy and paste

cd  /Users/username/Downloads/Open-Source-Battle-Bot-development 

python3 dokkan.py

every. time. lol.

If there could be some tips or solution given to make a shortcut to enter straight into the bot it would be incredibly helpful. Thanks flash, miss ya on disc

**Comment by PeterPlanlos** [comment]
Hi, i dont have macOS running so i cant test this but maybe it could help you and other macOS users.

1. create a file somewhere, name it: 
StartDokkan.sh

2. open that file and write into this:
#! /bin/bash
python3 /Users/username/Downloads/Open-Source-Battle-Bot-development/dokkan.py

3. for this step you need root rights or the hightest rights you can get on macOS. open your shell and type:
chmod 755 /your/path/to/StartDokkan.sh
this make your file executeable

after that you shoud be able to doubleclick your StartDokkan.sh file and it should start the python application. if doubleclick wont work try start your StartDokkan.sh with your shell ./StartDokkan.sh


*) on step 3 you should change the path: /your/path/to/
and if you want start the ./StartDokkan.sh with your shell you should add the correct path after .\ 

let me know if it helps you or if you have problems.

regards
Planlos
