### ISSUE TITLE
Stamina

### ISSUE THREAD

**Issue by Darpz** [FlashChaser/Open-Source-Battle-Bot#32]
Hi, I see you Say the Stamina bug has been patch but Can you give me the link of the new bot without this bug plz ? Thx

**Comment by pasatron10** [comment]
https://github.com/FlashChaser/Open-Source-Battle-Bot/issues/25

There is a guide to solve the problem

**Comment by Darpz** [comment]
Where ?

**Comment by Danbuc09** [comment]
I have been looking for that guide too lol

**Comment by BSNation** [comment]
Hey. There isn't a already **pre-complied** version of the bot, but uninstall the previous version of your bot, and follow the instructions here. 
https://docs.google.com/document/d/1zHZl6WNyAq_VXQ6jRc0xbSoEBX7YcK_pBTZxnS5aCpg/edit?usp=sharing
It's a little different in that you have to download some pip3 consoles from CMD and you're running a dokkan.py file through the desktop directory, however it shouldn't have any other differences. Setup may take longer but it's worth it to get rid of the stamina bug ;)

**Comment by Junni0** [comment]
not sure what im doing wrong myself. the cryptodrome pip didn't install or wasn't found for me. do I need to reinstall everything?

**Comment by benjamintoallstar** [comment]
I used the guide to install the bot, but I still get a stamina issue where I run out of stamina and the bot states that stamina is restored, but actually isn't. 
![Capture](https://user-images.githubusercontent.com/50959297/58264886-fd19d700-7dc1-11e9-948d-3d8fd4537c43.PNG)

**Comment by FlashChaser** [comment]
Check releases for new compiled version
