### ISSUE TITLE
latest commit giving errors

### ISSUE THREAD

**Issue by tgeisterfer** [FlashChaser/Open-Source-Battle-Bot#35]
http://prntscr.com/nsgf5n

it doesnt download the new database i believe. previous commits it would download it first and then i dont have the problem. but with this new 1 it doesnt download anything

**Comment by PeterPlanlos** [comment]
hi, i can confirm your problem.

you have to edit the help.txt
here you should see that
1558091524
1558404621
+some help text

change these numbers to just 111.

have fun 

regards Planlos

**Comment by tgeisterfer** [comment]
thank you!
