### ISSUE TITLE
CompleteZBattle command is skipping the EZA and only refreshing the token every time

### ISSUE THREAD

**Issue by NilBarua** [FlashChaser/Open-Source-Battle-Bot#36]
Hi,

Everytime I use the CompleteZBattle command on a **existing account** , it just skips the EZA while my EZA are only at levels like 11, this command does seem to work on brand new **accounts** that you farm right from scratch. Sometimes the EZA hasn't even been done yet and doesn't get cleared. I also tried updating the database to the newest version thinking that might had something to do with it but even that didn't work.

Anyways I only encountered this issue on Global & JP on the Open Source Bot and it doesn't seem to give any weird error code, just refreshes the tokens and skips the EZA right through.

![image](https://user-images.githubusercontent.com/34094775/58279152-ef525a80-7d9d-11e9-833c-46a27bdf5e59.png)
![image](https://user-images.githubusercontent.com/34094775/58279260-38a2aa00-7d9e-11e9-8b52-2a9bd64ed0a8.png)
![image](https://user-images.githubusercontent.com/34094775/58279280-43f5d580-7d9e-11e9-90ce-a7af206439eb.png)

If there's already a solution for this or so, please let me know cause I haven't seen any commits for the zbattle fix. Thanks.

**Comment by FlashChaser** [comment]
Can you test latest commit to double check that it resolved this issue?
