### ISSUE TITLE
TypeError('string indices must be integers') 

### ISSUE THREAD

**Issue by SuicideBooth** [FlashChaser/Open-Source-Battle-Bot#38]
![image](https://user-images.githubusercontent.com/50839300/58302313-c4422800-7dea-11e9-95f9-33e1542f0635.png)
Not exactly sure why I'm getting this. I'm afraid I have lost my main account because I can't access the transfer or id.

**Comment by PeterPlanlos** [comment]
it tells you that your account is transferred. did you screenshot to anybody your transfercode when you did create one or something like that?
