### ISSUE TITLE
GLB Stamina issue

### ISSUE THREAD

**Issue by benjamintoallstar** [FlashChaser/Open-Source-Battle-Bot#39]
Downloaded the bot yesterday, JP works as it should. But for GLB, the bot doesn't restore stamina.
![Capture](https://user-images.githubusercontent.com/50959297/58306844-3abd4500-7e40-11e9-83c8-66ba497dbc17.PNG)

**Comment by PeterPlanlos** [comment]
you did use the release right?

try using the  latest sourcecode. its already fixed.
on issue#25 you can get a instruction how to install python and how to run the application from source.

regards 
Planlos

**Comment by FlashChaser** [comment]
I've just uploaded a new compiled release to use.
