### ISSUE TITLE
To flash

### ISSUE THREAD

**Issue by SuicideBooth** [FlashChaser/Open-Source-Battle-Bot#43]
Please bring the commands from the first iteration of the bot to the new one, things like daily missions, log ins etc.

**Comment by tgeisterfer** [comment]
listmedals, list cards and kagi as well please :D

**Comment by FlashChaser** [comment]
Very happy to given time. Or if someone else helps out.

**Comment by FlashChaser** [comment]
I've opened up some projects for these.
https://github.com/FlashChaser/Open-Source-Battle-Bot/projects
