### ISSUE TITLE
ZBattle local variable 'level' referenced before assignment error,tripping again even after newest comitt

### ISSUE THREAD

**Issue by NilBarua** [FlashChaser/Open-Source-Battle-Bot#45]
So I'm trying to use the completezbattles command, works after the first time on a regular account, then I tried a few other accounts and it either refreshes the token each time or it shows this error.

Yes I have used the newest committs and updated the files and it's showing these errors and its refreshing tokens again, I don't know how but it happpened after I updated Globals database. The **first picture** was shown before I updated the database and the refresh token EZA is showing when I try to clear EZA and alot of EZA are still open for me.  In the **second picture** I try to complete  the EZA again but then it shows this error: {'error': {'code': 'no_condition_to_try_z_battle_is_fulfilled'}} and totally stops after the first EZA (Super Saiyan 3 Goku)

It's weird, it jumps from working to refreshing tokens & skipping EZA to {'error': {'code': 'no_condition_to_try_z_battle_is_fulfilled'}} .

Seems like the same error almost to me before the committs, works on brand new accounts just not on existing accounts. Any chance we could see the finishzbattle command from the old paid bot back into this one?

Anyways thanks for always helping guys, you're the best.

![image](https://user-images.githubusercontent.com/34094775/58368282-123e5500-7eeb-11e9-9136-0da859ed88b3.png)
![image](https://user-images.githubusercontent.com/34094775/58368810-5123d900-7ef2-11e9-8f98-d059891967b8.png)

**Comment by tgeisterfer** [comment]
http://prntscr.com/nt6can

can confirm newest commits. still having this error

**Comment by FlashChaser** [comment]
@tgeisterfer @NilBarua Can you try latest commit for me?

**Comment by tgeisterfer** [comment]
@FlashChaser will let you know

**Comment by tgeisterfer** [comment]
@FlashChaser yup should be good now. thank you!

**Comment by FlashChaser** [comment]
@tgeisterfer Finally, Ill close this for now but Ill reopen if its still buggy for others
