### ISSUE TITLE
On the global_run.exe i'm having trouble

### ISSUE THREAD

**Issue by Amumudubbz** [FlashChaser/Open-Source-Battle-Bot#47]
For some reason it keeps saying for anything im farming "('code' : 'act_is_not_enough')=stamina restored i enabled the dragon stones to be able to be used that didnt do anything any ideas?

**Comment by Amumudubbz** [comment]
I've downloaded the newest version but when I type in help it comes up with a line of numbers what do I do with these numbers im not sure

**Comment by Veladem** [comment]
The git has been updated, by Flash, and all act issues have been fixed please re-download and use the most recent release.
