### ISSUE TITLE
crypto 

### ISSUE THREAD

**Issue by zen11747** [FlashChaser/Open-Source-Battle-Bot#51]
it keeps saying No module named 'Crypto' everytime i try to run it

**Comment by Veladem** [comment]
go into your cmd/terminal, verify that you have python installed and path set. Then ensure pip is installed, (usually by default) and updated. Then install the missing dependencies via 
```
pip3 install 'module_name' --user
```
once your dependencies have been met you'll be able to run the dokkan.py or to bypass this grab the most recent Dokkan.zip and use the .exe to run the bot.
