### ISSUE TITLE
cant load older database

### ISSUE THREAD

**Issue by jserxxvd** [FlashChaser/Open-Source-Battle-Bot#54]
![bugs](https://user-images.githubusercontent.com/51057201/58385080-f59e3c00-8014-11e9-8df5-6745d4e47da1.png)

already reupdate database
and clone for newer bot
still got this problem

**Comment by NilBarua** [comment]
Save does not match client version means, that you're using the wrong version. So you're probably using a global save on a jp client.

**Comment by Veladem** [comment]
Please go back to the git, grab the first release source (Paid version without licensing), and run through dependency installations for dokkan.py. After doing so, load your saves onto that directory and use the report function to pull your saves from the .txt saves. After doing so you can use your transfer codes on the newest and most updated source/distribution.

**Comment by FlashChaser** [comment]
> Please go back to the git, grab the first release source (Paid version without licensing), and run through dependency installations for dokkan.py. After doing so, load your saves onto that directory and use the report function to pull your saves from the .txt saves. After doing so you can use your transfer codes on the newest and most updated source/distribution.

Older bot saves don't work with new bot. Best to transfer them in like @Veladem  said.
