### ISSUE TITLE
how can i fix this?

### ISSUE THREAD

**Issue by Gabbq** [FlashChaser/Open-Source-Battle-Bot#55]
![Immagine](https://user-images.githubusercontent.com/50996801/58423682-f3c88d00-8095-11e9-9fe9-6d98de48d185.png)

how can i fix this?

**Comment by EZucker98** [comment]
Press y when asked to look for new databases.

**Comment by Gabbq** [comment]
> 
> 
> Press y when asked to look for new databases.

it doesn't work, it give me an error andit doesn't work, when I try, I do the authentication and it gives me an error, after which it closes

**Comment by FlashChaser** [comment]
Where it says in your first error:
**```request ts expired```**
That means your computer clock isn't properly synchronised. Be sure to sync your computer with the internet.
