### ISSUE TITLE
Error with "pip3 install pycrypto - https://github.com/dlitz/pycrypto"

### ISSUE THREAD

**Issue by vAnoTiXn** [FlashChaser/Open-Source-Battle-Bot#59]
Sorry i'm getting started with python
And when i want to install this : (pip3 install pycrypto - https://github.com/dlitz/pycrypto)
I have an error : (Invalid requirement: '-')
Anyone can help me ?

**Comment by Veladem** [comment]
Try appending '--user' to the end of the command, lmk what happens.

**Comment by vAnoTiXn** [comment]
I found a solution but thanks a lot

**Comment by Veladem** [comment]
Please post the solution so others with the same question will have answers. Thanks!

**Comment by vAnoTiXn** [comment]
Just run : pip3 install pycryptodome

**Comment by KURO099** [comment]
I have the same problem
Can you tell me how you got the solution of that
