### ISSUE TITLE
Error when select event in GUI or stage command

### ISSUE THREAD

**Issue by Fateric95** [FlashChaser/Open-Source-Battle-Bot#63]
In Android Japan Server (build 0.1.1, actual JPN Database). When I select an active Dokkan event (Code, difficulty & times to do) in every attempt appears this error: {'code': 'the_number_of_cards_must_be_less_than_or_equal_to_the_capacity'}
I select all of decks (1 to 6), but still happens :(

**Comment by XUltraBeastX** [comment]
Sell your cards

**Comment by XUltraBeastX** [comment]
Or increase the capacity
