### ISSUE TITLE
active_record/record_not_found

### ISSUE THREAD

**Issue by FlyingPingu** [FlashChaser/Open-Source-Battle-Bot#68]
What does that mean ?
![Dokkan](https://user-images.githubusercontent.com/51376830/58894703-c3ff3200-86f2-11e9-8073-f0100d6ffb22.PNG)

**Comment by NilBarua** [comment]
Means that that stage has not been found for some reason, could be that it's not live or something anymore.

**Comment by FlyingPingu** [comment]
Thanks for your answer ! and what can i do ?

**Comment by FlyingPingu** [comment]
Just had to do the quest manualy
