### ISSUE TITLE
how do i get my account back on my phone

### ISSUE THREAD

**Issue by mustyfuk** [FlashChaser/Open-Source-Battle-Bot#69]

**Comment by ezeperezcrack** [comment]
Info(get your id)
Transfer(code)

**Comment by mustyfuk** [comment]
i cant get it back on my phone g idk if the commands work on mine i typed "Info", "Transfer" nothing.

**Comment by PeterPlanlos** [comment]
type info and grab your id and write it down anywhere.
after that type transfer and write your transfercode anywhere.
after that enter the data you wrote down anywhere to your phone.
