### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by EgemenGames603** [FlashChaser/Open-Source-Battle-Bot#87]
I have this problem when trying to farm? Anyone help?
![Capture](https://user-images.githubusercontent.com/49919491/60730481-8be34d00-9f45-11e9-90e0-b3de1707b27f.PNG)

**Comment by RyverLeague** [comment]
use the "refresh" command and try it again.

If this doesn't work relog your account

**Comment by EgemenGames603** [comment]
Thanks! It seems to be working now.
