### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by EZucker98** [FlashChaser/Open-Source-Battle-Bot#9]
![Capture](https://user-images.githubusercontent.com/50120370/57164767-bcc6ca80-6dba-11e9-832a-7f96b502e965.PNG)
Getting this error after trying any streamline or event. Any ideas?

**Comment by FlashChaser** [comment]
Are you using pycrypto or pycryptodome?

**Comment by EZucker98** [comment]
> Are you using pycrypto or pycryptodome?

Pycryptodome. Sorry for the late reply.

**Comment by thed24** [comment]
I believe its due to the way Python 3 handles encrypting, go to the encrypt_sign function, and create a new variable that takes in str.encode(data), and use that within the function instead of data.

**Comment by EZucker98** [comment]
> I believe its due to the way Python 3 handles encrypting, you want to convert the data being encrypted into bytes first, go to the encrypt_sign function, and create a new variable that takes in str.encode(data), and use that within the function instead of data.

Could you enlighten me on how to do that? I basically know nothing except from how to run the bot thanks to Thomas.

**Comment by XUltraBeastX** [comment]
> I believe its due to the way Python 3 handles encrypting, you want to convert the data being encrypted into bytes first, go to the encrypt_sign function, and create a new variable that takes in str.encode(data), and use that within the function instead of data.

**Comment by XUltraBeastX** [comment]
> I believe its due to the way Python 3 handles encrypting, you want to convert the data being encrypted into bytes first, go to the encrypt_sign function, and create a new variable that takes in str.encode(data), and use that within the function instead of data.

i have the same problem and i dont know how to do it

**Comment by XUltraBeastX** [comment]
> > I believe its due to the way Python 3 handles encrypting, you want to convert the data being encrypted into bytes first, go to the encrypt_sign function, and create a new variable that takes in str.encode(data), and use that within the function instead of data.
> 
> Could you enlighten me on how to do that? I basically know nothing except from how to run the bot thanks to Thomas.

it says that you can't concat a str and bytes after i did it.

**Comment by EZucker98** [comment]
Issue has been fixed with Thed24's pull.
